name: smartpay
description: A smart payment Flutter app with Firebase integration.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  font_awesome_flutter: ^10.12.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_analytics: ^11.4.4
  google_sign_in: ^6.2.1
  firebase_database: ^11.3.0
  firebase_data_connect: ^0.1.5+4 # âœ… Changed from ^0.2.0
  flutter_native_splash: ^2.4.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.11
  intl: ^0.20.2
  lottie: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.13.1

  # Optional for other code generation
  build_runner: ^2.4.8

flutter_native_splash:
  color: "#f4f4f4"
  image: "assets/images/logo.png"
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#f4f4f4"
    theme_color: "#2196F3"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/logo_black.png
    - assets/images/Nairobi.png
