name: smartpay
description: A smart payment Flutter app with Firebase integration.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  font_awesome_flutter: ^10.12.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Firebase (Updated for modern compatibility)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_analytics: ^12.0.4
  firebase_data_connect: ^0.2.1+2
  google_sign_in: ^6.2.1

  # Networking & Web
  http: ^1.2.1
  js: ^0.7.0
  web: ^1.1.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.11

flutter_native_splash:
  color: "#f4f4f4"
  image: "assets/images/logo.png"
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#f4f4f4"
    theme_color: "#2196F3"


flutter:
  uses-material-design: true

  assets:
    - assets/images/